version: '3.1'

services:
  backend:
    image: maven:3.6.0-jdk-8-alpine
    network_mode: host
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - 8081:8081
    command:
      mvn spring-boot:run -Dspring-boot.run.profiles=local

