server:
  servlet:
    session:
      timeout: 30d

spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  thymeleaf:
    prefix: classpath:templates/

email:
  retryLimit: 5
