server:
  port: 8080

  spring:
    cloud:
      gateway:
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedHeaders:
              - x-requested-with
              - authorization
              - Content-Type
              - Authorization
              - credential
              - X-XSRF-TOKEN
              - token
              - username
              - client
              allowedOrigins:
              - "http://localhost:3000"
              allowedMethods:
              - GET
