package shamu.company.authorization;

public enum Type {
  USER,
  USER_PERSONAL_INFORMATION,
  USER_ADDRESS,
  USER_CONTACT_INFORMATION,
  TIME_OFF_REQUEST,
  BENEFIT_PLAN,
  BENEFIT_DEPENDENT,
  TIME_OFF_POLICY_USER,
}
