package shamu.company.authorization;

public enum Type {
  USER,
  DEPARTMENT,
  USER_PERSONAL_INFORMATION,
  USER_ADDRESS,
  USER_CONTACT_INFORMATION,
  TIME_OFF_REQUEST,
  BENEFIT_PLAN,
  BENEFIT_DEPENDENT,
  TIME_OFF_POLICY_USER,
  TIME_OFF_POLICY,
  PAID_HOLIDAY,
  COMPANY_PAID_HOLIDAY,
  EMPLOYEE_COMPANY,
  JOB_TITLE,
  EMPLOYMENT_TYPE,
  OFFICE_LOCATION,
  USER_JOB,
  PAID_HOLIDAY_USER,
  TIME_OFF_USER,
}
