server:
  port: 8081

logging:
  level:
    root: INFO
    org:
      hibernate:
        type: trace
  config: classpath:log4j2-local.xml

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  profiles:
    include: database
  redis:
    host: localhost
    port: 6379

application:
  systemEmailAddress: no-reply@interviewed-qa.com
  frontEndAddress: http://localhost:3000/
  helpUrl: http://localhost:3000/
  systemEmailFirstName: SimplyHired
  systemEmailLastName: local
  googleGeoCodingApiKey: #{The key for google geocoding api}

cloud:
  aws:
    region:
      static: ap-northeast-1
      auto: false

aws:
  bucketName: simplyhired-hrs-eastbay-dev-company
  folder: media-local
  lambda:
    tenant-endpoint-token: #{any string}
  dynamodb:
    # This value just used to help local env start up successfully, the dynamodb table is an empty table
    table: local-unassigned-tenants


crypto:
  hash: system-hash
