server:
  port: 8081

logging:
  level:
    root: INFO
    org:
      hibernate:
        type: trace

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  profiles:
    include: database

application:
  systemEmailAddress: noreply@interviewed.com
  frontEndAddress: http://localhost:3000/

aws:
  awsAccessKeyId: AKIAXYMULKOL2JOY2GOP
  awsSecretAccessKey: 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
  bucketName: shamu-hrs-qa
  folder: media-local
  region: ap-northeast-1

auth0:
  algorithm: RS256

sendGrid:
  apiKey: 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
