server:
  port: 8081

logging:
  level:
    root: INFO
    org:
      hibernate:
        type: trace

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  profiles:
    include: database
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  redis:
    host: localhost
    port: 6379
    expiration: 36000

application:
  systemEmailAddress: noreply@interviewed.com
  frontEndAddress: http://localhost:3000/
  helpUrl: http://localhost:3000/

cloud:
  aws:
    region:
      static: ap-northeast-1
      auto: false

aws:
  bucketName: shamu-hrs-qa
  folder: media-local

auth0:
  domain: shamu-develop.auth0.com
  managementIdentifier: https://shamu-develop.auth0.com/api/v2/
