server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://shamu-hrs-qa.cenqdgeoqsjh.ap-northeast-1.rds.amazonaws.com/shamu_hrs_qa
    username: shamu_hrs_qa
    password: shamu_hrs_qa
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
  thymeleaf:
    cache: false

application:
  systemEmailAddress: noreply@interviewed.com
  frontEndAddress: http://shamu-hrs-qa.s3-website-ap-northeast-1.amazonaws.com/
