server:
  servlet:
    session:
      timeout: 30d

spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: false
        jdbc:
          time_zone: UTC
    show-sql: false
  liquibase:
    company:
      enabled: true
      change-log: classpath:/db/changelog/db.default.changelog-master.yml
    tenant:
      enabled: true
      change-log: classpath:/db/changelog/db.tenant.changelog-master.yml
    secret:
      enabled: true
      change-log: classpath:/db/changelog/db.secret.changelog-master.yml
  thymeleaf:
    prefix: classpath:templates/
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  mvc:
    locale: en_US
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  quartz:
    jdbc-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            useProperties: false
            dataSource: myDs
  http:
    encoding:
      enabled: true
  datasource:
    tenant-prefix: tenant_
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 20

cloud:
  aws:
    stack:
      auto: false

aws:
  secretsmanager:
    prefix: /secret
    enabled: true
    fail-fast: false

email:
  retryLimit: 5

auth0:
  algorithm: RS256
  audience: hrs-backend
  jwks: https://${auth0.domain}/.well-known/jwks.json
  customNamespace: https://interviewed.com/

user:
  cached:
    expiration: 36000
  invitationRateLimiting:
    maxPerMinute: 3
    maxPerDay: 200

timeOff:
  requestRateLimiting:
    maxPerHour: 30

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
        requestInterceptors:
          shamu.company.common.config.FeignAuthInterceptor

