server:
  port: 9000

spring:
  thymeleaf:
    cache: false

application:
  systemEmailAddress: noreply@SimplyHired.com
  frontEndAddress: https://hrs.interviewed-qa.com/

aws:
  bucketName: shamu-hrs-qa-company
  folder: media

cloud:
  aws:
    region:
      auto: true

## Sentry
sentry:
  enable: true
  dsn: https://76139c3c2fa24b6a832e34e3d772b4c9@sentry.io/1781126
  env: qa
  release: v1
