server:
  port: 8081

logging:
  level:
    root: INFO
    org:
      hibernate:
        type: trace

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  profiles:
    include: database

application:
  systemEmailAddress: noreply@interviewed.com
  frontEndAddress: http://localhost:3000/
  helpUrl: http://localhost:3000/

cloud:
  aws:
    region:
      static: ap-northeast-1
      auto: false

aws:
  bucketName: shamu-hrs-qa
  folder: media-local

auth0:
  algorithm: RS256
