server:
  servlet:
    session:
      timeout: 30d

spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  secret:
    liquibase:
      enabled: true
      change-log: classpath:/db/changelog/db.secret.changelog-master.yml
  thymeleaf:
    prefix: classpath:templates/
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  mvc:
    locale: en_US
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
cloud:
  aws:
    stack:
      auto: false

aws:
  secretsmanager:
    prefix: /secret
    enabled: true
    fail-fast: false

email:
  retryLimit: 5

auth0:
  algorithm: RS256
  audience: hrs-backend
  jwks: https://${auth0.domain}/.well-known/jwks.json
  customNamespace: https://interviewed.com/
