server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://hrs.cenqdgeoqsjh.ap-northeast-1.rds.amazonaws.com/company
    username: shamuhrs
    password: 4eD852HheH9DLykD
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
  thymeleaf:
    cache: false

application:
  systemEmailAddress: noreply@interviewed.com
  frontEndAddress: http://localhost:3000/
