server:
  port: 9000

spring:
  thymeleaf:
    cache: false

application:
  systemEmailAddress: noreply@interviewed.com
  frontEndAddress: https://hrs.interviewed-qa.com/

aws:
  bucketName: shamu-hrs-qa
  folder: media

cloud:
  aws:
    region:
      auto: true