server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://shamu-hrs-dev.cenqdgeoqsjh.ap-northeast-1.rds.amazonaws.com/company?zeroDateTimeBehavior=convertToNull
    username: shamuhrs
    password: 4eD852HheH9DLykD
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
  thymeleaf:
    cache: false

application:
  systemEmailAddress: noreply@interviewed.com
  frontEndAddress: http://localhost:3000/

aws:
  awsAccessKeyId: AKIAXYMULKOL2JOY2GOP
  awsSecretAccessKey: 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
  bucketName: shamu-hrs-qa
  folder: media-local
  region: ap-northeast-1
