void setBuildStatus(String message, String state) {
    step([
            $class            : "GitHubCommitStatusSetter",
            reposSource       : [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/tardisone/shamu-hrs-company-service.git"],
            contextSource     : [$class: "ManuallyEnteredCommitContextSource", context: "shamu-company-master-build"],
            errorHandlers     : [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
            statusResultSource: [$class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]]]
    ])
}

pipeline {
    agent { label 'shamu-hrs' }
    stages {
        stage('pull shamu-hrs') {
            steps {
                sh 'mkdir -p shamu-hrs'
                dir('shamu-hrs') {
                    git branch: "master",
                    credentialsId: "${credentialsId}",
                    url: 'https://github.com/tardisone/shamu-hrs-autoscale-test.git'
                }
            }
        }
        stage('unit tests') {
            steps {
                withCredentials([string(credentialsId: 'sonarqube-token', variable: 'TOKEN')]) {
                    echo '---------------------------------\n' +
                            '            Unit test            ' +
                            '\n---------------------------------'
                    sh '''
                        current_commit_id=`git rev-parse --short HEAD`
                        mvn clean test sonar:sonar \
                          -Dsonar.host.url=http://3.115.71.39 \
                          -Dsonar.login=$TOKEN \
                          -Dsonar.projectKey=shamu-hrs-company-service \
                          -Dsonar.projectName=shamu-hrs-company-service \
                          -Dsonar.projectVersion="$current_commit_id" \
                          -Dsonar.sources=src/main/java \
                          -Dsonar.java.binaries=target \
                          -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-output/coverage-report-unit-tests/jacoco.xml \
                          -Dsonar.tests=target/test-classes
                       '''
                }
            }
        }
        stage('create ansible vault file') {
            steps {
                script {
                    withCredentials([string(credentialsId: "simplyhired-hrs-eastbay-dev-ansible-vault", variable: 'ANSIBLE_VAULT')]){
                        sh "echo $ANSIBLE_VAULT > ansible-vault-file"
                    }
                }
            }
        }
        stage('create artifact for dev environment') {
            steps {
                echo '---------------------------------\n' +
                        '      Create artifact         ' +
                        '\n---------------------------------'
                script {
                  WORKSPACE = sh(returnStdout: true, script: 'pwd')
                }
                sh "ansible-playbook shamu-hrs/auto-deploy/ansible/create-project-config-files.yml -e 'workspace=${WORKSPACE} stack_prefix=simplyhired-hrs-eastbay env=dev service_name=company' --vault-password-file ansible-vault-file"
                sh "CI/build -e simplyhired-hrs-eastbay-dev -r master"
            }
        }
        stage('deploy company service') {
            steps {
                script {
                    sh "CI/deploy simplyhired-hrs-eastbay-dev master"
                }
            }
        }
    }
    post {
        success {
            setBuildStatus("Build succeeded", "SUCCESS")
        }
        failure {
            setBuildStatus("Build failed", "FAILURE")
        }
        always {
            cleanWs()
        }
    }
}
