void setBuildStatus(String message, String state) {
    step([
            $class            : "GitHubCommitStatusSetter",
            reposSource       : [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/tardisone/shamu-hrs-company-service.git"],
            contextSource     : [$class: "ManuallyEnteredCommitContextSource", context: "shamu-company-master-build"],
            errorHandlers     : [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
            statusResultSource: [$class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]]]
    ])
}

pipeline {
    agent any
    stages {
        stage('unit tests') {
            steps {
                echo '---------------------------------\n' +
                        '            Unit test            ' +
                        '\n---------------------------------'

                sh "mvn clean test -Dspring.profiles.active=test > junit_output.txt"
            }
        }
        stage('create artifact') {
            steps {
                echo '---------------------------------\n' +
                        '      Create artifact         ' +
                        '\n---------------------------------'
                script {
                    // ref: ref/release/0.1.x -> RELEASE: 0.1.x
                    RELEASE = sh(returnStdout: true, script: ''' echo ${ref} | sed 's/^.*\\///' ''').trim()
                    if (RELEASE == "" || RELEASE == "master") {
                        RELEASE = 'master'
                        sh(returnStdout: false, script: "git checkout origin/master")
                        sh(returnStdout: false, script: "CI/build -e ${params.DEV_ENV} -r ${RELEASE}")
                    } else {
                        sh(returnStdout: false, script: "git checkout ${ref}")
                        sh(returnStdout: false, script: "CI/build -e ${params.QA_ENV} -r ${RELEASE}")
                    }
                }
            }
        }
        stage('deploy company service') {
            steps {
                script {
                    if (RELEASE == 'master') {
                        // deploy company service to dev environment
                        sh "git checkout origin/master && CI/deploy ${params.DEV_ENV} ${RELEASE}"
                    } else {
                        // deploy company service to qa environment
                        sh "git checkout ${ref} && CI/deploy ${params.QA_ENV} ${RELEASE}"
                    }
                }
            }
        }
    }
    post {
        success {
            setBuildStatus("Build succeeded", "SUCCESS")
        }
        failure {
            setBuildStatus("Build failed", "FAILURE")
        }
    }
}
