void setBuildStatus(String message, String state) {
    step([
            $class            : "GitHubCommitStatusSetter",
            reposSource       : [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/tardisone/shamu-hrs-company-service.git"],
            contextSource     : [$class: "ManuallyEnteredCommitContextSource", context: "shamu-company-master-build"],
            errorHandlers     : [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
            statusResultSource: [$class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]]]
    ])
}

pipeline {
    agent any
    environment {
        sonarqubeScannerHome = tool name: 'Shamu Hrs Company Service Sonarqube Scanner'
    }
    stages {
        stage('unit tests') {
            steps {
                echo '---------------------------------\n' +
                        '            Unit test            ' +
                        '\n---------------------------------'

                sh "mvn clean test -Dspring.profiles.active=test > junit_output.txt"
            }
        }
        stage('sonarqube analysis') {
            steps {
                echo '---------------------------------\n' +
                        '      SonarQube analysis         ' +
                        '\n---------------------------------'
                withSonarQubeEnv('ShamuHrsCompanyServiceSonarQube') {
                    sh "${sonarqubeScannerHome}/bin/sonar-scanner"
                }
            }
        }
        stage('create artifact') {
            steps {
                echo '---------------------------------\n' +
                        '      Create artifact         ' +
                        '\n---------------------------------'
                script {
                    RELEASE = sh(returnStdout: true, script: ''' echo ${ref} | sed 's/^.*\\///' ''').trim()
                    REF = sh(returnStdout: true, script: "echo ${ref}").trim()
                    if (RELEASE == "") {
                        RELEASE = 'master'
                        REF = 'origin/master'
                    }
                }
                sh "git checkout ${REF} && CI/build -e ${params.DEV_ENV} -e ${params.QA_ENV} -r ${RELEASE}"
            }
        }
        stage('deploy master to dev environment') {
            when {
                expression { RELEASE == 'master' }
            }
            steps {
                sh "git checkout origin/master && CI/deploy ${params.DEV_ENV} ${RELEASE}"
            }
        }
    }
    post {
        success {
            setBuildStatus("Build succeeded", "SUCCESS")
        }
        failure {
            setBuildStatus("Build failed", "FAILURE")
        }
    }
}
