env:
  browser: true
  es6: true
extends: airbnb
parser: 'babel-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  ORIGIN: true
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {}

settings:
  import/resolver:
    webpack:
      config: ./config/webpack.config.js
